spack:
  definitions:
  - pkgs:
    - gcc@12
    - git
    - patch
    - flex
    - bison
    - hwloc
    - python@3
    - py-cython
    - cmake
    - ninja
    - otf2@2.3
    - openmpi
    - openblas
    - scalapack

  view: true
  specs:
    - matrix:
      - [$pkgs]
